version: '3.8'

services:
  # MinIO сервис
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9090"
    volumes:
      - minio-data:/data

  # Flask-приложение 1
  flask-app1:
    build:
      context: ./app1
      dockerfile: Dockerfile
    container_name: flask-app1
    ports:
      - "5000:5000"
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      APP2_URL: http://flask-app2:5001  # Адрес второго контейнера
    depends_on:
      - minio
      - flask-app2
    command: >
      sh -c "sleep 5 && python app.py"

  # Flask-приложение 2
  flask-app2:
    build:
      context: ./app2
      dockerfile: Dockerfile
    container_name: flask-app2
    ports:
      - "5001:5001"
    depends_on:
      - minio
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: >
      sh -c "sleep 5 && python app.py"

volumes:
  minio-data:
    driver: local
